package com.example.demo.helpers;
// Generated by Selenium IDE

import com.example.demo.ApplicationManager;

import org.openqa.selenium.Dimension;

public class NavigationHelper extends HelperBase {
    private String baseUrl;

    public NavigationHelper(ApplicationManager manager) {
        driver = manager.getDriver();
    }

    public void getSiteUrl() {
        driver.get("http://web.bossnote.ru/signIn/");
        driver.manage().window().setSize(new Dimension(1100, 900));
    }

    public void getProfileUrl() {
        driver.get("http://web.bossnote.ru/index/");
    }

    public void setBaseUrl(String url) {
        baseUrl = url;
    }
}
