package com.example.demo.generators;
// Generated by Selenium IDE
import com.example.demo.helpers.LoginHelper;
import com.example.demo.helpers.NoteHelper;
import com.example.demo.models.AccountData;
import com.example.demo.models.NoteData;
import com.example.demo.models.jaxb.Notes;
import com.example.demo.models.jaxb.Users;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;


public class Generator {
    public static final String DIRECTORY = "C:\\Users\\Home\\IdeaProjects\\demo";

    public static void main(String[] args) {
        String type = args[0];
        int count = Integer.parseInt(args[1]);
        String filename = args[2];
        String format = args[3];
        if (Objects.equals(type, "note")) GenerateForGroups(count, filename, format);
        else if (Objects.equals(type, "user")) GenerateForUsers(count, filename, format);
        else throw new IllegalArgumentException("Unrecognized type of data: " + type);
    }

    private static void GenerateForGroups(int count, String filename, String format) {
        List<NoteData> notes = new LinkedList<>();
        for (int i = 0; i < count; i++) {
            notes.add(new NoteData(NoteHelper.getRandomString(3, 10, 5, 18)));
//            System.out.println(notes);
        }
        System.out.println(notes);
        if (Objects.equals(format, "xml")) {
            try (FileWriter fileWriter = new FileWriter(DIRECTORY + "/" + filename + "." + format)) {
                writeNotesToXmlFile(notes, fileWriter);
            } catch (IOException exception) {
                throw new RuntimeException(exception);
            }
        } else {
            throw new IllegalArgumentException("Unrecognized format: " + format);
        }
    }

    static void writeNotesToXmlFile(List<NoteData> noteDataList, FileWriter fileWriter) {
        try {
            Notes notes = new Notes();
            notes.setNotes(noteDataList);
            JAXBContext jaxbContext = JAXBContext.newInstance(Notes.class);
            Marshaller marshaller = jaxbContext.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            marshaller.marshal(notes, fileWriter);
        } catch (JAXBException e) {
            throw new RuntimeException(e);
        }
    }

    private static void GenerateForUsers(int count, String filename, String format) {
        List<AccountData> users = new LinkedList<>();
        for (int i = 0; i < count; i++) {
            users.add(new AccountData(
                    LoginHelper.getRandomUsername(1, 1, 5, 18),
                    LoginHelper.getRandomPassword(1, 1, 5, 18)));
        }
        if (Objects.equals(format, "xml")) {
            try (FileWriter fileWriter = new FileWriter(DIRECTORY + "/" + filename + "." + format)) {
                writeUsersToXmlFile(users, fileWriter);
            } catch (IOException exception) {
                throw new RuntimeException(exception);
            }
        } else {
            throw new IllegalArgumentException("Unrecognized format: " + format);
        }
    }

    private static void writeUsersToXmlFile(List<AccountData> userDataList, FileWriter fileWriter) {
        try {;
            Users users = new Users();
            users.setUsers(userDataList);
            JAXBContext jaxbContext = JAXBContext.newInstance(Users.class);
            Marshaller marshaller = jaxbContext.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            marshaller.marshal(users, fileWriter);
        } catch (JAXBException e) {
            throw new RuntimeException(e);
        }
    }
}