package com.example.demo.Tests;
// Generated by Selenium IDE

import com.example.demo.ApplicationManager;
import com.example.demo.generators.Generator;
import com.example.demo.helpers.AuthBase;
import com.example.demo.models.AccountData;

import com.example.demo.models.NoteData;
import com.example.demo.models.jaxb.Notes;
import com.example.demo.models.jaxb.Users;
import org.junit.Assert;
import org.junit.Test;
import org.junit.experimental.theories.DataPoints;
import org.junit.experimental.theories.Theories;
import org.junit.experimental.theories.Theory;
import org.junit.runner.RunWith;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.File;
import java.util.List;
import java.util.Objects;

@RunWith(Theories.class)
public class Test0002 extends AuthBase {
//    AccountData user = new AccountData("adelya6387240@gmail.com", "pokdfghQ1");

    //    NoteData note = new NoteData("hello");
    @DataPoints
    public static List<NoteData> notesFromXmlFile() {
        try {
            JAXBContext context = JAXBContext.newInstance(Notes.class);
            Unmarshaller unmarshaller = context.createUnmarshaller();
            Notes notes = (Notes) unmarshaller.unmarshal(new File(Generator.DIRECTORY + "/output.xml"));
            return notes.getNotes();
        } catch (JAXBException exception) {
            throw new RuntimeException(exception);
        }
    }

    @Test
    @Theory
    public void test3(NoteData notes) throws InterruptedException {
//        app.getNavigation().getSiteUrl();
//        app.getAuth().Login(user);
//        super.setUpTest();
        ApplicationManager.getNote().addNote(notes);
        Assert.assertEquals(notes.getRecord(), ApplicationManager.getNote().getLastNote());
    }
}
